version: '3.2'

services:
  node0:
    image: verim-node
    build: .
    ports:
      - "26656:26656" # p2p
      - "26657:26657" # rpc
    volumes:
      - ./node_configs/node0:/home/verim/.verimnode:Z
    command: start --rpc.laddr tcp://0.0.0.0:26657 --p2p.persistent_peers "${NODE_0_ID}@node0:26656,${NODE_1_ID}@node1:26656,${NODE_2_ID}@node2:26656,${NODE_3_ID}@node3:26656"

  node1:
    image: verim-node
    build: .
    ports:
      - "26659:26656" # p2p
      - "26660:26657" # rpc
    volumes:
      - ./node_configs/node1:/home/verim/.verimnode:Z
    command: start --rpc.laddr tcp://0.0.0.0:26657

  node2:
    image: verim-node
    build: .
    ports:
      - "26662:26656" # p2p
      - "26663:26657" # rpc
    volumes:
      - ./node_configs/node2:/home/verim/.verimnode:Z
    command: start --rpc.laddr tcp://0.0.0.0:26657

  node3:
    image: verim-node
    build: .
    ports:
      - "26665:26656" # p2p
      - "26666:26657" # rpc
    volumes:
      - ./node_configs/node3:/home/verim/.verimnode:Z
    command: start --rpc.laddr tcp://0.0.0.0:26657
